### ISSUE TITLE
t/multi.t fails on WIN10 StrawberryPerl 5.32.1.1

### ISSUE THREAD

**Issue by stryk187** [DrHyde/perl-modules-CPAN-FindDependencies#11]
E:\tmp>cpanm -v CPAN::FindDependencies
cpanm (App::cpanminus) 1.7044 on perl 5.032001 built for MSWin32-x64-multi-thread
Work directory is E:\strawberry-perl-5.32.1.1-64bit-portable\data/.cpanm/work/1614113921.15288
You have make E:\strawberry-perl-5.32.1.1-64bit-portable\c\bin\gmake.exe
You have LWP 6.52
Falling back to Archive::Tar 2.38
Searching CPAN::FindDependencies () on cpanmetadb ...
--> Working on CPAN::FindDependencies
Fetching http://www.cpan.org/authors/id/D/DC/DCANTRELL/CPAN-FindDependencies-3.04.tar.gz ... OK
Unpacking CPAN-FindDependencies-3.04.tar.gz
Entering CPAN-FindDependencies-3.04
Checking configure dependencies from META.json
Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (7.58)
Running Makefile.PL
Configuring CPAN-FindDependencies-3.04 ... Checking if your kit is complete...
Looks good
Generating a gmake-style Makefile
Writing Makefile for CPAN::FindDependencies
Writing MYMETA.yml and MYMETA.json
OK
Checking dependencies from MYMETA.json ...
Checking if you have CPAN::Meta 0 ... Yes (2.150010)
Checking if you have File::Temp 0.19 ... Yes (0.2311)
Checking if you have Test::Time 0 ... Yes (0.08)
Checking if you have Devel::CheckOS 1.52 ... Yes (1.85)
Checking if you have Test::Differences 0 ... Yes (0.67)
Checking if you have Capture::Tiny 0.05 ... Yes (0.48)
Checking if you have LWP::Protocol::https 6.09 ... Yes (6.10)
Checking if you have Parse::CPAN::Packages 2.31 ... Yes (2.40)
Checking if you have ExtUtils::MakeMaker 0 ... Yes (7.58)
Checking if you have URI::file 4.13 ... Yes (5.06)
Checking if you have Win32::Job 0 ... Yes (0.05)
Checking if you have Text::Diff 0 ... Yes (1.45)
Checking if you have LWP::Simple 0 ... Yes (6.52)
Checking if you have Scalar::Util 1.14 ... Yes (1.55)
Checking if you have Archive::Zip 0 ... Yes (1.68)
Checking if you have File::Type 0 ... Yes (0.22)
Checking if you have Module::CoreList 5.20200920 ... Yes (5.20210123)
Checking if you have Archive::Tar 0 ... Yes (2.38)
Checking if you have Test::More 0.88 ... Yes (1.302183)
Checking if you have File::Find::Rule 0 ... Yes (0.34)
Checking if you have File::Path 2.17 ... Yes (2.18)
Building and testing CPAN-FindDependencies-3.04 ... cp lib/CPAN/FindDependencies/Dependency.pm blib\lib\CPAN\FindDependencies\Dependency.pm
cp lib/CPAN/FindDependencies/MakeMaker.pm blib\lib\CPAN\FindDependencies\MakeMaker.pm
cp lib/CPAN/FindDependencies.pm blib\lib\CPAN\FindDependencies.pm
"E:\strawberry-perl-5.32.1.1-64bit-portable\perl\bin\perl.exe" -MExtUtils::Command -e cp -- bin/cpandeps blib\script\cpandeps
pl2bat.bat blib\script\cpandeps
"E:\strawberry-perl-5.32.1.1-64bit-portable\perl\bin\perl.exe" -MExtUtils::Command -e cp -- bin/cpandeps-diff blib\script\cpandeps-diff
pl2bat.bat blib\script\cpandeps-diff
"E:\strawberry-perl-5.32.1.1-64bit-portable\perl\bin\perl.exe" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib\lib', 'blib\arch')" t/*.t
t/configure.t ................................ ok
t/cpandeps-diff-script.t ..................... ok
t/cpandeps-script.t .......................... ok
t/dependencies.t ............................. ok
t/makefilepl.t ............................... ok
t/maxdepth.t ................................. ok
t/multi.t .................................... WARNING: CPAN::FindDependencies: Can't unbzip2 C:\Users\USER1\AppData\Local\Temp\CPAN-FindDependencies-jTVeF2Jp: No such file or directory
No data could be read from file at E:\strawberry-perl-5.32.1.1-64bit-portable\data\.cpanm\work\1614113921.15288\CPAN-FindDependencies-3.04\blib\lib/CPAN/FindDependencies.pm line 540.
Can't call method "list_files" on an undefined value at E:\strawberry-perl-5.32.1.1-64bit-portable\data\.cpanm\work\1614113921.15288\CPAN-FindDependencies-3.04\blib\lib/CPAN/FindDependencies.pm line 543.
t/multi.t .................................... Dubious, test returned 9 (wstat 2304, 0x900)
No subtests run
t/nometa-nowarnings-fatalerrors-nocaching.t .. skipped: Need web access to the CPAN
t/pod-coverage.t ............................. ok
t/pod.t ...................................... ok
t/recommended.t .............................. ok

Test Summary Report
-------------------
t/multi.t                                  (Wstat: 2304 Tests: 0 Failed: 0)
  Non-zero exit status: 9
  Parse errors: No plan found in TAP output
Files=11, Tests=25, 22 wallclock secs ( 0.03 usr +  0.03 sys =  0.06 CPU)
Result: FAIL
Failed 1/11 test programs. 0/25 subtests failed.
gmake: *** [Makefile:918: test_dynamic] Error 255
FAIL
! Installing CPAN::FindDependencies failed. See E:\strawberry-perl-5.32.1.1-64bit-portable\data\.cpanm\work\1614113921.15288\build.log for details. Retry with --force to force install it.

**Comment by DrHyde** [comment]
I assume that this will work if you install `bzip2`. I'll update the tests to skip that one if it's not available, although note that this obviously means that dependencies of modules distributed in bz2 files can't be detected.

**Comment by DrHyde** [comment]
Fix is in 24bb0ab if you want it before it hits the CPAN - that will be some time tomorrow cos it's past my bed time :-)

**Comment by DrHyde** [comment]
Version 3.05 should hit your local CPAN mirror shortly. Thanks for the report.
