### ISSUE TITLE
Cpan::Finddependencies | full dependency list are not shown in list

### ISSUE THREAD

**Issue by AbinayaSandhiyaM** [DrHyde/perl-modules-CPAN-FindDependencies#12]
Hi,

we found some issues with the current CPAN::Finddependencies.

1. The dependency for DBI is as shown below [ DBI Dependencies ]
2. the first level nested dependency for ExtUtils::MakeMaker is  ends with Scalar::Util
3. But in reality Scalar::Util have dependencies as shown in log [ Scalar:: Util dependencies ]

So our question is why the dependency tree for DBI excludes actual dependencies of Scalar::Util.

[ DBI Dependencies ]

DBI (T/TI/TIMB/DBI-1.643.tar.gz)
 ExtUtils::MakeMaker (B/BI/BINGOS/ExtUtils-MakeMaker-7.62.tar.gz)
  Encode (D/DA/DANKOGAI/Encode-3.10.tar.gz)
   Exporter (T/TO/TODDR/Exporter-5.74.tar.gz)
    Carp (X/XS/XSAWYERX/Carp-1.50.tar.gz)
     IPC::Open3 (X/XS/XSAWYERX/perl-5.34.0.tar.gz)
     Test::More (E/EX/EXODIST/Test-Simple-1.302185.tar.gz)
      File::Temp (E/ET/ETHER/File-Temp-0.2311.tar.gz)
       File::Path (J/JK/JKEENAN/File-Path-2.18.tar.gz)
        File::Spec::Functions (X/XS/XSAWYERX/PathTools-3.75.tar.gz)
         **Scalar::Util (P/PE/PEVANS/Scalar-List-Utils-1.56.tar.gz)**
       parent (C/CO/CORION/parent-0.238.tar.gz)
      Storable (X/XS/XSAWYERX/Storable-3.15.tar.gz)
       XSLoader (S/SA/SAPER/XSLoader-0.24.tar.gz)
  Pod::Man (R/RR/RRA/podlators-4.14.tar.gz)
   Pod::Simple (K/KH/KHW/Pod-Simple-3.42.tar.gz)
    Pod::Escapes (N/NE/NEILB/Pod-Escapes-1.07.tar.gz)
    Test (J/JE/JESSE/Test-1.26.tar.gz)
    Text::Wrap (M/MU/MUIR/modules/Text-Tabs+Wrap-2013.0523.tar.gz)
    if (X/XS/XSAWYERX/if-0.0608.tar.gz)

[ Scalar:: Util dependencies ]

Scalar::Util (P/PE/PEVANS/Scalar-List-Utils-1.56.tar.gz)
 Test::More (E/EX/EXODIST/Test-Simple-1.302185.tar.gz)
  File::Temp (E/ET/ETHER/File-Temp-0.2311.tar.gz)
   Carp (X/XS/XSAWYERX/Carp-1.50.tar.gz)
    Exporter (T/TO/TODDR/Exporter-5.74.tar.gz)
    IPC::Open3 (X/XS/XSAWYERX/perl-5.34.0.tar.gz)
   File::Path (J/JK/JKEENAN/File-Path-2.18.tar.gz)
    File::Spec::Functions (X/XS/XSAWYERX/PathTools-3.75.tar.gz)
   parent (C/CO/CORION/parent-0.238.tar.gz)
  Storable (X/XS/XSAWYERX/Storable-3.15.tar.gz)
   XSLoader (S/SA/SAPER/XSLoader-0.24.tar.gz)

**Comment by AbinayaSandhiyaM** [comment]
will provide more details as per your requests

**Comment by DrHyde** [comment]
Note that all of Scalar::Util's dependencies are listed somewhere in the tree for DBI. They were just pulled into the dependency list by some other dependency.

CPAN::FindDependencies only lists any one dependency in the tree once. I shall improve the documentation to make that clearer.

**Comment by AbinayaSandhiyaM** [comment]
Hi,

Thanks for the update.

Any possibilities to get detailed output

for ex,

DBI list itself detailed dependencies of Scalar::Utils should be listed.

**Comment by DrHyde** [comment]
Version 3.06 will be on the CPAN shortly with documentation on how the tree is pruned.

If you want to add an option to retrieve the full tree, with duplicates, then I would welcome a pull request. This should include documentation and thorough tests for both the module and for the `bin/cpandeps` script, and all the existing tests should still pass. Don't forget to cope with circular dependencies!

**Comment by AbinayaSandhiyaM** [comment]
Thanks for your suggestion

I could see the documentation https://metacpan.org/dist/CPAN-FindDependencies/view/bin/cpandeps mentioned as below

TREE PRUNING
The dependency tree is pruned to remove duplicates. This means that even though Test::More, for example, is a dependency of 
almost everything on the CPAN, it will only be listed once.

could understand that dependencies tree removing duplicates from the lists

but our requirement is we dont want to remove duplicates entries and should get clear dependencies

would be great if you could develop any option for this ...

thanks!

**Comment by DrHyde** [comment]
You either need to implement this yourself (and, as above, I would gratefully apply a patch), or pay me to implement it.
