### ISSUE TITLE
Test suite fails if devel version of Net::SSLeay is installed

### ISSUE THREAD

**Issue by eserte** [DrHyde/perl-modules-CPAN-FindDependencies#5]
On one of my systems (where I am forced to install a devel version of Net::SSLeay because of problems with openssl 1.1.1) IO::Socket::SSL throws warnings (@noxxi: FYI), which causes the CPAN-FindDependencies test suite to fail:
```
#   Failed test 'Spew to STDERR was suppressed: Argument "1.86_06" isn't numeric in numeric lt (<) at /usr/perl5.28.0p/lib/site_perl/5.28.0/IO/Socket/SSL.pm line 94.
# '
#   at t/03-makefilepl.t line 36.
# Looks like you failed 1 test of 6.
t/03-makefilepl.t ...............................
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/6 subtests

#   Failed test 'no errors reported'
#   at t/04-script.t line 47.
#          got: 'Argument "1.86_06" isn't numeric in numeric lt (<) at /usr/perl5.28.0p/lib/site_perl/5.28.0/IO/Socket/SSL.pm line 94.'
#     expected: ''
# Looks like you failed 1 test of 4.
t/04-script.t ...................................
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/4 subtests
```

**Comment by DrHyde** [comment]
I can't replicate this on my Mac, at least using the most recent IO::Socket::SSL. What version are you using?

**Comment by eserte** [comment]
I cannot replicate it anymore on that freebsd system with the newest CPAN::FindDependencies. Theory: the previous version used http://search.cpan.org URLs, which got redirected to https URLs. Now everything probably uses http and IO::Socket::SSL is never loaded.

**Comment by DrHyde** [comment]
That sounds plausible. All the URLs in the code are http. I'll close the ticket then.
